In [1]:
import numpy as np
import matplotlib.pyplot as plt
from nbody import Particles 

# The `Particles` class

We could write a `Particles` python class to handle the particle information.
The class contains several physical properties, including tag, mass, position, velocity, acceleration, and time.

For our own convenience, we want to have the below data type to handle the N-body simulation:

In [2]:
time          = 0    # the starting  time
num_particles = 100  # number of particles
masses        = np.ones((num_particles,1))
positions     = np.zeros((num_particles,3)) # 3 directions
velocities    = np.zeros((num_particles,3))
accelerations = np.zeros((num_particles,3))
tags          = np.linspace(1,num_particles,num_particles)

Note that, the mass is setting to a Nx1 martrix.\
The reason to use Nx1 matrix but not a 1D numpy array is because mass x velcoity is the momentum\
and only Nx1 matrix could multiple with an Nx3 matrix.

The particles class can be initialized by

In [3]:
particles = Particles(N=num_particles)

In [4]:
particles.masses = np.ones((num_particles,1))
particles.positions = np.random.rand(num_particles, 3)
particles.velocities = np.random.rand(num_particles, 3)
particles.accelerations = np.random.rand(num_particles, 3)
particles.tags = np.linspace(1,num_particles,num_particles)
print(particles.accelerations)

[[9.80175947e-01 9.87964213e-01 7.71735268e-01]
 [6.07923472e-02 5.95596484e-02 6.70033584e-01]
 [6.66565617e-01 5.63538369e-01 9.53569814e-01]
 [6.38589316e-01 6.62870904e-01 5.69128060e-01]
 [2.95457570e-01 4.75528701e-01 5.35837511e-01]
 [2.97954433e-01 2.01030073e-01 6.47831640e-01]
 [1.60511584e-01 1.07363448e-02 3.22142466e-01]
 [8.21855411e-01 5.51544050e-01 5.02321049e-01]
 [6.94946862e-01 1.65630129e-01 5.67439767e-01]
 [6.69325563e-01 8.88940276e-01 2.74223578e-01]
 [3.14968400e-01 4.79863125e-03 1.75107542e-01]
 [6.48379237e-02 3.46566817e-01 1.85045425e-01]
 [2.67329687e-01 1.46379173e-01 4.05918315e-01]
 [4.49624591e-01 1.58940214e-01 5.69339375e-01]
 [5.76454753e-01 9.79832037e-01 8.82430406e-01]
 [7.90225757e-02 3.70292236e-01 4.92219978e-01]
 [9.12167345e-01 8.18196073e-01 9.42023861e-01]
 [2.28234403e-01 5.69773976e-01 3.37431693e-01]
 [3.07495796e-01 8.14538601e-01 7.49383922e-01]
 [6.32058277e-01 3.33327709e-01 4.01053926e-01]
 [5.00773801e-02 6.35396656e-01 4.528567

Make sure your code will check the shape of your inputs. It must return errors when setting an incorrect shape.

In [ ]:
# make sure the below codes will return an error. uncomment each line to test

# particles.masses = np.ones(num_particles)
# particles.positions = np.random.rand(199, 3)
# particles.velocities = np.random.rand(500, 3)
# particles.accelerations = np.random.rand(num_particles, 2)
# particles.tags = np.linspace(1,num_particles,500)

# Add (remove) more particles

We could add more particles on the fly.

In [ ]:
num_particles = 20
masses = np.ones((num_particles,1))
positions = np.random.rand(num_particles, 3)
velocities = np.random.rand(num_particles, 3)
accelerations = np.random.rand(num_particles, 3)

particles.add_particles(masses, positions, velocities, accelerations)
print(particles.nparticles)
print(particles._masses.shape)
print(particles._positions.shape)



### Data IO

We could also dump the particle information into a text file.

In [ ]:
# particles.output(filename='data.txt')
particles.save_data('Nbady_number_120_time_0')


### Visualization

We could also visualize (both 2D and 3D) these particles

In [ ]:
particles.plot_output(2)

In [ ]:
particles.plot_output(3)

# Exercise 1

Implment the `Particles` class in `./nbody/particles.py`. Please make sure your Particles class has passed all the test in the above section. 

In [ ]:
# TODO: test your class here
particles = Particles(N=num_particles)

import sys 
sys.path.append('../project1/solver')



# Exercise 2

Once you have the `Particles` class implmented correctly.\
You should be able to use it to initialzie arbitry distribution of N particles.

(1) Initialize two particles that describe the Sun-Earth binary system.

(2) Initialize a 3D particle clould with N=1000 particles in a normal distrbuiotn (sigma=1) and total mass equal to 10.

Hints: use `numpy.random.randn` (see https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html). 

In [ ]:
# TODO:
import sys 
sys.path.append('../project1')
import solver as mysolver     
num_particles = 1000
total_mass=10
particles = Particles(N=num_particles)
particles.masses  = np.random.randn(num_particles, 1)+1/num_particles*total_mass
particles.positions = np.random.rand(num_particles, 3)
particles.velocities = np.random.rand(num_particles, 3)
particles.accelerations = np.random.rand(num_particles, 3)
particles.tags = np.linspace(1,num_particles,num_particles)

particles.plot_output(2)




